services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop-reroll
    container_name: shop-reroll
    restart: unless-stopped
    ports:
      - "10002:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
